### ISSUE TITLE
Change the way we handle the modal

### ISSUE THREAD

**Issue by MuhannedNoman** [FatimaAlmashhor/capstone-project-exhale#116]
Let'e have one modal to handle both Login and Signup 
The use clicked the button to Sign In 
The modal show with the Login form as default. 
![image](https://user-images.githubusercontent.com/40465727/98780762-563a5800-2406-11eb-92a5-11f5e23566bf.png)
Then If he wants to Signup he can change the Tab and go to Signup Tab inside the same Modal. 
I think this will fix the bug we are facing now.

**Comment by MuhannedNoman** [comment]
This way the Google and FB buttons are always there you just switch tabs to see login or Signup

**Comment by FatimaAlmashhor** [comment]
but I think they have separate processing function ??, I hate the idea of tab but I will fix the Google and Facebook issue
