### ISSUE TITLE
Card > Component

### ISSUE THREAD

**Issue by MuhannedNoman** [FatimaAlmashhor/capstone-project-exhale#17]
This should render a Card component to the screen, that should take other components as children.

Variations: 
https://material.io/components/cards
Focus: ![image](https://user-images.githubusercontent.com/40465727/96424654-a8bb9680-1203-11eb-8f39-8dd08eed4626.png)
Border: 
![image](https://user-images.githubusercontent.com/40465727/96424682-b3762b80-1203-11eb-9a71-9e5af4fb8e8f.png)
Normal : 
![image](https://user-images.githubusercontent.com/40465727/96424733-c7219200-1203-11eb-8645-6ef9ef670d6c.png)

**Comment by FatimaAlmashhor** [comment]
@MuhannedNoman I get confused on this !!

**Comment by MuhannedNoman** [comment]
@FatimaAlmashhor 
```
<Card>  
   <WhateverContentIhave />
</Card>
```
This is what I want the final result to look like. A Component that takes other components as children and render them. 
Does this clear things for you ?

**Comment by FatimaAlmashhor** [comment]
@MuhannedNoman  so you mean by this like frame component ? just have a border and hover design ?!!!
