### ISSUE TITLE
Component > Image

### ISSUE THREAD

**Issue by MuhannedNoman** [FatimaAlmashhor/capstone-project-exhale#49]
This should render an image component that we pass an svg component for and can control the width, height and fill color.

**Comment by FatimaAlmashhor** [comment]
@MuhannedNoman  is it common item ? and about the filling the color we will pass the color from the image as props then  to SVG component as props as well ?

**Comment by MuhannedNoman** [comment]
It is common, for the color I think something that will fill the color here not in the svg component.
