### ISSUE TITLE
Component/Design > Our values

### ISSUE THREAD

**Issue by MuhannedNoman** [FatimaAlmashhor/capstone-project-exhale#51]
This should render a component like the one in the image. 
image will be in the right one time and on the left the other time.
We also need Designs for the images. 
![image](https://user-images.githubusercontent.com/40465727/97112381-03b62780-16f5-11eb-915f-1a48ebb3d130.png)

**Comment by FatimaAlmashhor** [comment]
@MuhannedNoman  what we going to add on it ?? to do  this big slider let just change the stars to icons and I think no time for designing right now let just change the team card in about us page .What do you think ?

**Comment by MuhannedNoman** [comment]
Will copy over something from another site. We are not creating something new here remember that !!
