### ISSUE TITLE
articles page

### ISSUE THREAD

**Issue by FatimaAlmashhor** [FatimaAlmashhor/capstone-project-exhale#95]
the article page need fix in search section it is too big , margin top of the whole page and container for some shrink  .
@DhiaaAlshamy  you did not use the service > fakeArticleService

one more thing we need to add see more loading to show other articles like social media infinite scrolling .

**Comment by DhiaaAlshamy** [comment]
@FatimaAlmashhor , I used to fake articles,  and see more in the other pull request
